# Generated by Django 2.2.4 on 2019-11-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191111_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='about.jpg', upload_to='photos'),
        ),
    ]
