# Generated by Django 2.2.4 on 2019-11-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FS', 'Fashion'), ('ET', 'Electronics'), ('FT', 'Furniture'), ('PT', 'Phones & Tablets')], max_length=2),
        ),
    ]
