# Generated by Django 2.2.4 on 2019-11-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='trend',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('H', 'HOT'), ('S', 'SALE')], max_length=2, null=True),
        ),
    ]
