# Generated by Django 2.2.4 on 2019-11-02 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_item_trend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
