# Generated by Django 2.2.4 on 2019-11-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
