# Generated by Django 2.2.4 on 2019-11-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_cartitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='title',
        ),
    ]
