# Generated by Django 2.2.4 on 2019-12-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20191202_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
