# Generated by Django 2.2.4 on 2019-12-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20191207_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
