# Generated by Django 2.2.4 on 2019-12-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20191209_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='cart_items',
        ),
    ]
