# Generated by Django 2.2.4 on 2019-12-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20191209_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(blank=True, to='pages.CartItem'),
        ),
    ]
