# Generated by Django 2.2.4 on 2019-12-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_remove_order_billing_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='default',
        ),
    ]
