# Generated by Django 2.2.4 on 2020-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20200529_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_1',
            field=models.ImageField(default='2.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_2',
            field=models.ImageField(default='2.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_3',
            field=models.ImageField(default='2.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_4',
            field=models.ImageField(default='2.jpg', upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo_5',
            field=models.ImageField(default='2.jpg', upload_to='photos'),
        ),
    ]
